version: '3.8'

services:
  django:
    container_name: chat_app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "
            python manage.py migrate &&
            daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    container_name: chat_db
    image: postgis/postgis:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5434:5432"

  redis:
    container_name: chat_redis
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume:
